TOP=../..

include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS BELOW HERE

# xxxRecord.h will be created from xxxRecord.dbd
DBDINC += xxxRecord

# Install xxxSupport.dbd into <top>/dbd
DBD += xxxSupport.dbd

# Build an IOC support library
LIBRARY_IOC += nsls2-stdIOCSupport

# Compile and add the code to the support library
nsls2-stdIOCSupport_SRCS += xxxRecord.c
nsls2-stdIOCSupport_SRCS += devXxxSoft.c

# Link locally-provided code into the support library,
# rather than directly into the IOC application.
# This is required for Windows DLL builds.
nsls2-stdIOCSupport_SRCS += dbSubExample.c
nsls2-stdIOCSupport_SRCS += nsls2-stdIOCHello.c
nsls2-stdIOCSupport_SRCS += initTrace.c

nsls2-stdIOCSupport_LIBS += $(EPICS_BASE_IOC_LIBS)


# Build the IOC application
PROD_IOC = nsls2-stdIOC

# nsls2-stdIOC.dbd will be created and installed
DBD += nsls2-stdIOC.dbd

# nsls2-stdIOC.dbd will include these files:
nsls2-stdIOC_DBD += base.dbd
nsls2-stdIOC_DBD += xxxSupport.dbd
nsls2-stdIOC_DBD += dbSubExample.dbd
nsls2-stdIOC_DBD += nsls2-stdIOCHello.dbd
nsls2-stdIOC_DBD += initTrace.dbd

# nsls2-stdIOC_registerRecordDeviceDriver.cpp derives from nsls2-stdIOC.dbd
nsls2-stdIOC_SRCS += nsls2-stdIOC_registerRecordDeviceDriver.cpp

# Build the main IOC entry point where needed
nsls2-stdIOC_SRCS_DEFAULT += nsls2-stdIOCMain.cpp
nsls2-stdIOC_SRCS_vxWorks += -nil-

# Link in the code from our support library
nsls2-stdIOC_LIBS += nsls2-stdIOCSupport

# To build SNL programs, SNCSEQ must be defined
# in the <top>/configure/RELEASE file
ifneq ($(SNCSEQ),)
    # Build sncExample into nsls2-stdIOCSupport
    sncExample_SNCFLAGS += +r
    nsls2-stdIOC_DBD += sncExample.dbd
    # A .stt sequence program is *not* pre-processed:
    nsls2-stdIOCSupport_SRCS += sncExample.stt
    nsls2-stdIOCSupport_LIBS += seq pv
    nsls2-stdIOC_LIBS += seq pv

    # Build sncProgram as a standalone program
    PROD_HOST += sncProgram
    sncProgram_SNCFLAGS += +m
    # A .st sequence program *is* pre-processed:
    sncProgram_SRCS += sncProgram.st
    sncProgram_LIBS += seq pv
    sncProgram_LIBS += $(EPICS_BASE_HOST_LIBS)
endif

# Finally link IOC to the EPICS Base libraries
nsls2-stdIOC_LIBS += $(EPICS_BASE_IOC_LIBS)

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD EXTRA GNUMAKE RULES BELOW HERE

